export const about = "Welcome to Code Nexus, a no-nonsense programming practice website!<br />At Code Nexus, we believe in empowering aspiring programmers to reach their full potential through tailored learning experiences. Whether you're aiming for a career at tech giants like Google, Facebook, or Amazon, or honing your skills for any other esteemed company, we've got you covered.<br />Our platform leverages cutting-edge artificial intelligence to generate practice questions customized to your target company and chosen data structures. Gone are the days of generic exercises that barely scratch the surface of what you'll encounter in real-world coding interviews.<br/> With Code Nexus, you'll dive deep into the specific challenges you'll face, sharpening your problem-solving abilities and boosting your confidence along the way.<br /><br />"
+"<b>IMPORTANT</b><img class='about-icon' src='../assets/icons/important.svg' /><br/>"
+"CodeNexusAI is not like other platforms where you run your code against few testcases.<br/>"
+"Our platform uses Advance AI to change the way you prepare for interviews!<img class='about-icon' src='../assets/icons/ai2.svg' /><br/>"
+"Here the focus will be on your <b>logic</b> because that is what matters the most in an interview.<img class='about-icon' src='../assets/icons/interview.svg'/><br/>"
+"This approach of solving problems helps you harness and increase your problem solving capability by simulating an interview experience.<br/>"
+"All the options with <img class='about-icon' src='../assets/icons/lock.svg'/> icon can be unlocked with premium subscription."
+"With <em><u>PREMIUM</u></em> subscription, you can get additional features like getting hints, points to optimize your code and all other future updates!"
export const autoAdaptInfo = "You are in Auto-Adapt mode, the questions here start from Easy level, then based on your performance, the subsequent questions difficulty will increase."

export const premiumSubscriptionDetails = "Monthly Subscription at INR 150 /-"
export const premiumSubscriptionBody = "Get Access to all our PREMIUM features listed below and also any future updates that we release!"
export const premiumToolTip = "Unlock with PREMIUM access"
